title: "Overherd"
description: "Here, I share ideas, tools, and methods that help me balance productivity with creativity while keeping control over my digital world."
url: "https://anantshiva.github.io"
baseurl: "" # important for GitHub Pages

author:
  name: "Anant Shiva"
  bio: "Yet another guy on the internet with opinions."
  avatar: "/images/01-1.jpg"

permalink: /:title/
paginate: 6
paginate_path: /page:num/

repository: smartyshaman/anantshiva.github.io

# Exclude _site and other folders so they don’t get pushed unnecessarily
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - CNAME
  - .sass-cache
  - .jekyll-cache
  - .github

markdown: kramdown
theme: null

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
