#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anantshiva.github.io" # the base hostname & protocol for your site, e.g. http://example.com
title: "Overherd"  # your site title
description: "Yet another guy on the internet with opinions."  # for SEO
author: "Anant Shiva"

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  style: compressed