#-------------------------------
# Site Settings
title: Overherd
description: #
logo: # You can add own logo. For example '/images/logo.png'.
logo_dark:


#-------------------------------
# Color Scheme Settings
color_scheme:
  default: dark # Default theme applied on the first visit (options: "light" or "dark")
  toggle: true # Enable theme toggle

# Enables or disables the theme toggle functionality:
# - true: Users can switch between light and dark modes using a toggle button.
#          The site will remember their choice for future visits.
# - false: The theme will always use the default mode specified above,
#          and the toggle button will not be displayed.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Videos'
      url: '/videos/'
    - title: 'Archive'
      url: '/archive/'
    - title: 'Pages'
      submenu:
      - url: '/about/'
        title: 'About'
      - url: '/contact/'
        title: 'Contact'
      - url: '/elements/'
        title: 'Elements'


#-------------------------------
# Author Settings
author:
  author_name: Anant Shiva
  author_avatar: /images/01-1.jpg


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_avatar: /images/01-1.jpg
  hero_title: Hi! I’m Anant 👋
  hero_subtitle: Yet another guy on the internet with opinions.
  hero_description: |
    I teach video production and storytelling, but I also like figuring things out — whether it’s messing with code until something <em>kind of</em> works, building better habits, or making sense of the world.

    This blog is where I share what I’m learning, what I’m experimenting with, and whatever’s on my mind. If that sounds like your kind of thing, stick around.
  hero_image: /images/01.jpg
  hero_image_caption: My creative space, where masterpieces are born
  hero_button_text: Get in touch
  hero_button_link: '/contact/'


#-------------------------------
# Section Blog Settings
blog:
  enable: true
  blog_title: The Binary Journal

#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Stay inspired weekly ✌️
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Join Now


#-------------------------------
# Footer Settings
footer_description: Here, I share ideas, tools, and methods that help me balance productivity with creativity while keeping control over my digital world. Dive in, get inspired, and feel free to share your thoughts!


#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
- {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com"}
- {icon: "fa-solid fa-rss", name: "Rss", link: "/feed.xml"}

# Example of adding a new link to the sidebar and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: your@email.com # Add your form_id
  button_text: Send Now

# NOTE
# Coderon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title: Start the conversation
  disqus_button_text: Show Comments


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id